apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-mysql-backend
  namespace: server
spec:
  selector:
    matchLabels:
      app: express-mysql-backend
  template:
    metadata:
      labels:
        app: express-mysql-backend
    spec:
      containers:
      - name: server-container
        # image: olaranmmy/expressmysql_backend:20260423-140953
        image: olaranmmy/expressmysql_backend:latest
        ports:
        - containerPort: 80

        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_HOST

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_PASSWORD

          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_NAME

          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_PORT

          - name: SERVER_PORT
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: SERVER_PORT
