apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-mysql-backend
  namespace: server
spec:
  selector:
    matchLabels:
      app: express-mysql-backend
  template:
    metadata:
      labels:
        app: express-mysql-backend
    spec:
      containers:
      - name: server-container
        image: olaranmmy/expressmysql_backend:20260423-140953
        # image: olaranmmy/expressmysql_backend:latest
        ports:
        - containerPort: 80
