apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: server
data:
type: Opaque
stringData:
  DB_HOST: database-1.c8taiy0ywcgt.us-east-1.rds.amazonaws.com
  DB_USER: admin
  DB_PASSWORD: password
  DB_NAME: expressmysql
  DB_PORT: "3306"
  SERVER_PORT: "5000"

