kind: Service
apiVersion: v1
metadata:
  name:  express-mysql-backend-service
  namespace:  server
spec:
  selector:
    app:  express-mysql-backend
  type:  LoadBalancer
  ports:
  - name:  express-mysql-backend-port
    port:  80
    targetPort:  5000