apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-mysql-frontend
  namespace: client
spec:
  selector:
    matchLabels:
      app: express-mysql-frontend
  template:
    metadata:
      labels:
        app: express-mysql-frontend
    spec:
      containers:
      - name: client-container
        image: olaranmmy/expressmysql_frontend:20260423-140953
        ports:
        - containerPort: 80
