name: "ci runner for expressMysql frontend"
on: 
  push:
    branches:
      - master
env:
  FRONTEND_IMAGE_NAME: expressmysql_frontend
  BACKEND_IMAGE_NAME: expressmysql_backend
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - name:  checkout to root directory
      uses: actions/checkout@v6

    - name: Generate timestamp tag
      run: echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: build docker image using dockerfile in respective directory
      run: |
        sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./app/client
        sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./app/server


    - name: Login to dockerhub
      run: |
        sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: push the images built to dockerhub
      run: |
        sudo docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        sudo docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}


